### ISSUE TITLE
Kernel Headers

### ISSUE THREAD

**Issue by rylev** [microsoft/wdkmetadata#1]
It would be fantastic to be able to use this crate for kernel mode development (e.g., drivers), but it seems so far the metadata is limited to user-mode bindings. Is Kernel mode development in scope for this metadata?

**Comment by mikebattista** [comment]
Closing this out as this issue primarily tracked standing up a central place to build out WDK metadata, which is completed.

I've created separate issues for the specific APIs that were requested here. New requests should be filed as separate issues.

**Comment by mikebattista** [comment]
The windows crate is now wired up to consume the metadata from this repo! See https://github.com/microsoft/windows-rs/pull/2358#issue-1601820082.

As the metadata is built out here, bindings will be automatically generated in the windows crate!
