### ISSUE TITLE
NtCreateFile function enums

### ISSUE THREAD

**Issue by AArnott** [microsoft/wdkmetadata#15]
The [`NtCreateFile`](https://learn.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile) method parameters could use some enum love:

- [ ] `DesiredAccess` parameter is currently declared as uint, but it ought to be as this `FILE_ACCESS_FLAGS` enum.
- [ ] `FileAttributes` parameter should be declared as a FILE_ATTRIBUTES enum. Previously suggested to be `FILE_FLAGS_AND_ATTRIBUTES` but @KalleOlaviNiemitalo made a good comment in https://github.com/microsoft/win32metadata/issues/1440#issuecomment-1402709728 to consider.
- [ ] `CreateOptions`  (#1441)
- [ ] Remove `NtCreateFile` from the [SDK metadata](https://github.com/microsoft/win32metadata) as part of this change

See also discussion in microsoft/win32metadata#1440.

If `NtCreateFile` is in the WDK, it's already in the win32metadata, so... do we remove it, or fix the enums?

**Comment by kennykerr** [comment]
So the function was removed from the win32 metadata and added to the wdk metadata? We'll need a matching release of both to avoid a missing function issue.
