### ISSUE TITLE
Add support for D3DKMT* APIs in d3dkmthk.h

### ISSUE THREAD

**Issue by xeysz** [microsoft/wdkmetadata#21]
I use the [D3DKMT* APIs](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/) a lot to test [WDDM](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/windows-vista-display-driver-model-design-guide) drivers. I currently use bindgen for these APIs since they're neither in winapi-rs, windows, or windows-sys, but I'd love to see them officially supported here 😃.

**Comment by mikebattista** [comment]
What is the full set of headers you include for this to compile?

**Comment by xeysz** [comment]
This is all I use for the `D3DKMT*` functions and types

```C
#include <Windows.h>
#include <d3dkmthk.h>
```

**Comment by mikebattista** [comment]
Thanks. Once we ship an update here these APIs should be available in the windows crate under `Windows.Wdk.Graphics.Direct3D`.
