### ISSUE TITLE
FILE_DISPOSITION_* constants missing

### ISSUE THREAD

**Issue by rbtcollins** [microsoft/wdkmetadata#22]
FILE_DISPOSITION_DO_NOT_DELETE | 0x00000000 
FILE_DISPOSITION_DELETE | 0x00000001 
FILE_DISPOSITION_POSIX_SEMANTICS | 0x00000002 
FILE_DISPOSITION_FORCE_IMAGE_SECTION_CHECK | 0x00000004 
FILE_DISPOSITION_ON_CLOSE | 0x00000008 
FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE | 0x00000010 

FileDispositionInfoEx is defined, just not the constants for it.

**Comment by ChrisDenton** [comment]
I think these are defined with the `FILE_DISPOSITION_FLAG_` prefix instead of just `FILE_DISPOSITION_`.

**Comment by rbtcollins** [comment]
Huh yes, seem to be - https://github.com/search?q=repo%3Amicrosoft%2Fwdkmetadata+FILE_DISPOSITION_FLAG_DELETE&type=code. They would be more discoverable if the name was the same as that in the SDK documentation on learn.microsoft.com :(.

**Comment by ChrisDenton** [comment]
Hm, it seems the WDK should be using the `FILE_DISPOSITION_` constants but the SDK should use `FILE_DISPOSITION_FLAG_`. The meaning and values are the same for both so it does seem a bit silly to repeat them but I guess the API designers wanted to give themselves room for future values to diverge.
