### ISSUE TITLE
Invalid nested types

### ISSUE THREAD

**Issue by kennykerr** [microsoft/wdkmetadata#26]
Some types include invalid field types that I can't parse. They're considered nested types but the names are invalid since "@void*" is not a valid/existing nested type name. 

```C#
.field public valuetype [Windows.Wdk.winmd]Windows.Wdk.System.SystemServices.IO_DRIVER_CREATE_CONTEXT/@void* pSystemMem
```

<img width="337" alt="image" src="https://user-images.githubusercontent.com/9845234/229810094-1cc31623-a89c-4ea2-af6e-379656f2bf08.png">

<img width="554" alt="image" src="https://user-images.githubusercontent.com/9845234/229809936-072a9f5b-c417-4e68-880c-2fb0f7ba990d.png">

**Comment by mikebattista** [comment]
All of these instances are typed as `const void *` in the header. I'm not familiar with this `@` symbol or why it's showing up in this case. You can see they all have the `[Const`] attribute, so we're picking that up at least.

**Comment by mikebattista** [comment]
This appears to be caused by how ECP_LIST is getting scraped and then remapped.

**Comment by kennykerr** [comment]
Thanks, the internal build looks good.
