### ISSUE TITLE
Invalid function imports 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/wdkmetadata#30]
The latest build appears to include invalid function imports. Functions like:

```C#
[DllImport("CLFS", ExactSpelling = true, PreserveSig = false)]
public static extern void ClfsFinalize();
```

And also:

```C#
[DllImport("ksecdd", ExactSpelling = true, PreserveSig = false)]
public unsafe static extern SspiAsyncContext* SspiCreateAsyncContext();
```

To begin with, they lack a file extension so it's unclear how to link them.

Note that some of these may not even be DLLs to begin with (they may be .sys files) but I'm not sure how you determine that when generating the metadata. 

Also, I though all library names should be lowercase but that doesn't appear to be enforced consistently across the Win32 and WDK metadata.

**Comment by riverar** [comment]
We closed the lowercase PR in favor of raw_dylib https://github.com/microsoft/win32metadata/issues/648. API to lib mappings is handled in [libmappings.rsp](https://github.com/microsoft/wdkmetadata/blob/main/generation/WDK/libMappings.rsp) and will need some corrections.

**Comment by mikebattista** [comment]
As @riverar said, [libmappings.rsp](https://github.com/microsoft/wdkmetadata/blob/main/generation/WDK/libMappings.rsp) is where these are defined.

7ab660565753342dd9f0d91737957c84692bdf62 was used to prepopulate this but the script and the output will need some scrutiny. The script was modified from the equivalent win32metadata script.

**Comment by mikebattista** [comment]
How should .exe., .drv, and .sys be handled? Should we just exclude those or can we support them?

**Comment by kennykerr** [comment]
They should work - we just need them to be explicit.

**Comment by kennykerr** [comment]
Thanks, checking now.

**Comment by kennykerr** [comment]
Yep, looks good - thanks!

**Comment by mikebattista** [comment]
Thanks. I published another update.
