### ISSUE TITLE
Support d3dhal.h

### ISSUE THREAD

**Issue by mikebattista** [microsoft/wdkmetadata#34]
This header was excluded from the SDK metadata since it covers kernel mode display driver scenarios.

**Comment by mikebattista** [comment]
@damyanp I could use some feedback on how to handle a few d3d headers between the SDK and WDK metadata.

* d3dhal.h
* d3dnthal.h
* d3dcaps.h
* d3dtypes.h

The hal headers I believe make sense here in the WDK metadata but they depend on the other two I believe which are currently not being scraped in the SDK metadata.

Do you agree? If so, which metadata and in what namespace(s) would you suggest d3dcaps.h and d3dtypes.h belong?

**Comment by damyanp** [comment]
Aren't d3dcaps.h and d3dtypes.h going into Windows.Win32.System.SystemServices in the SDK metadata?

**Comment by mikebattista** [comment]
They're not included in the corresponding main.cpp so they aren't being scraped right now. They need to be moved out of there anyway even if they were.

**Comment by damyanp** [comment]
Ok.  I think these are all D3D9 things, so they would correspond to Windows.Win32.Graphics.Direct3D9, I'm double checking.

**Comment by jenatali** [comment]
Yeah, d3dcaps.h and d3dtypes.h are D3D9 (and older) headers. There's `#if` blocks in the (IIRC) to be able to include them as D3D8, or D3D7, or older, but they default to D3D9.

**Comment by mikebattista** [comment]
Thanks. I will put d3dcaps and d3dtypes in Windows.Win32.Graphics.Direct3D9 and the hal headers in Windows.Wdk.Graphics.Direct3D.

**Comment by mikebattista** [comment]
[Added d3dcaps.h and d3dtypes.h to Direct3D9.](https://github.com/microsoft/win32metadata/commit/fde770eeab993c4c0bd8cb1072a536b879e5c084)
