### ISSUE TITLE
`Windows.Wdk.Foundation.IRP` refers to `Windows.Win32.Graphics.DirectDraw.MDL`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/wdkmetadata#35]
Somehow, I don't think the WDK depends on DirectDraw.

**Comment by kennykerr** [comment]
For the most part, I'd expect only references to `Windows.Win32.Foundation` types. At the moment the following additional type dependencies exist:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/9845234/235029875-0b80ab99-d418-4e6f-af3a-30ab901ffc74.png">

**Comment by mikebattista** [comment]
MDL in the SDK should move to Windows.Win32.Foundation.

For the rest, I don't agree with your premise that the WDK metadata should only depend on Windows.Win32.Foundation. Would need more specific feedback to be actionable.

**Comment by kennykerr** [comment]
I don't know what your philosophy is for namespace dependencies. I'm just pointing out that the dependency graph is a bit chaotic right now. For example, to call the `FsRtlBalanceReads` function you need to include a dependency on the following namespaces:

* Windows.Wdk.Foundation
* Windows.Wdk.System.SystemServices
* Windows.Win32.Foundation
* Windows.Win32.Graphics.DirectDraw
* Windows.Win32.Security
* Windows.Win32.System.Kernel
* Windows.Win32.System.Power
* Windows.Win32.System.WindowsProgramming

I don't know what the answer is in general, but it may be that the current namespace scheme is really untenable for C/C++/Rust languages and we'll have to derive our own partitioning scheme algorithmically.

**Comment by mikebattista** [comment]
I'm not surprised by that given the experimental nature of the metadata.

In general, I'd expect Windows.Wdk.System.Threading to depend on APIs from Windows.Win32.System.Threading, Windows.Wdk.Storage.FileSystem to depend on Windows.Win32.Storage.FileSystem, etc. Where it makes sense to move SDK types to Windows.Win32.Foundation we can do that, but I don't think the goal is 100% of WDK dependencies are on Foundation.
