### ISSUE TITLE
MEMORY_BASIC_INFORMATION declared in WDK and SDK

### ISSUE THREAD

**Issue by AArnott** [microsoft/wdkmetadata#42]
Having the struct declared twice may be problematic to consumers and projections alike.
CsWin32 in particular happens to have a test for generating this struct and ran into the issue when two structs were generated.

But the two structs are not equivalent today. The declaration in the SDK has an extra `PartitionId` field in the middle of the list. So either there's a bug in one of them, or they are in fact two distinct structs.
If this is truly by design, I'll try to fix up CsWin32 to not fail.

**Comment by mikebattista** [comment]
Looks like a duplicate that should be removed from here.
