### ISSUE TITLE
Feature request: NtLoadDriver support

### ISSUE THREAD

**Issue by Nariod** [microsoft/wdkmetadata#43]
### Motivation

Hello,

I know you are not porting low level NTAPI to Rust in this project, but IMO this one is a bit special. The `NtLoadDriver` call is easy to call from C/C++, but is really hard not to mess in Rust due to the pointer to UNICODE_STRING as parameter.
Source: https://docs.rs/ntapi/latest/ntapi/ntioapi/fn.NtLoadDriver.html

Could you consider supporting this very specific NTAPI function in windows-rs ?
All the best !

### Drawbacks

Main drawback:
- If you port this, you will have to maintain an undocumented NTAPI function

### Rationale and alternatives

- Support another way to easily load drivers in Windows using Rust

**Comment by mikebattista** [comment]
Would be covered by https://github.com/microsoft/win32metadata/issues/1722 as ZwLoadDriver is currently in the metadata just not the Nt equivalent.
