### ISSUE TITLE
Support Ndis.h

### ISSUE THREAD

**Issue by DropDemBits** [microsoft/wdkmetadata#50]
Currently trying to follow the [ndisprot_kmdf](https://github.com/microsoft/Windows-driver-samples/tree/main/network/ndis/ndisprot_kmdf) example in my [ndisprot-rs](https://github.com/DropDemBits/ndisprot-rs/) project, and `ndis.h` is particularly annoying to generate bindings for due to depending on msvc-specific behaviour (see the code for [the workaround](https://github.com/DropDemBits/ndisprot-rs/blob/b254a2db89640bab745a389880544d006d9edd1d/driver/windows-kernel-sys/build.rs#L163-L167) I do), so it'd be nice for wdkmetadata to support it instead. :grinning:

I technically generate bindings for NDIS 6.82, but am technically registering as an NDIS 6.0 protocol driver so generating metadata for the latest NDIS version would be fine with me.

Thanks!

**Comment by DropDemBits** [comment]
Apparently `NdisRegisterProtocolDriver` or `PNDIS_BIND_PARAMETERS` (which are both gated behind `NDIS_SUPPORT_NDIS6`) aren't showing up in the metadata, which seems to be caused by the defines made in `ndis/version.h` not being visible inside of `ndis.h`.

> There are a bunch of "ndis" headers other than just ndis.h so you'll have to tell me if I got the full closure of what's needed.

It seems like the only header that's missing is `netpnp.h`, though once `NET_PNP_EVENT_NOTIFICATION` (gated behind `NDIS_SUPPORT_NDIS6`) is scraped it'd be needed anyways.

**Comment by mikebattista** [comment]
Thanks I created a separate issue for these.
