### ISSUE TITLE
Missing DEVPKEY_s

### ISSUE THREAD

**Issue by Nuklon** [microsoft/wdkmetadata#56]
Defined using DEFINE_DEVPROPKEY in km/bthguid.h.

**Comment by Nuklon** [comment]
Also in km/NFCDriverDDI.h and km/ksmedia_phone.h

**Comment by mikebattista** [comment]
I don't see NFCDriverDDI.h or ksmedia_phone.h anywhere. Where are those from?

**Comment by Nuklon** [comment]
> I don't see NFCDriverDDI.h or ksmedia_phone.h anywhere. Where are those from?
They're in Win10 SDK:
https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/km/ksmedia_phone.h
https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/km/NFCDriverDDI.h

**Comment by Nuklon** [comment]
> Given they're phone related, not in the latest kits, and have no documentation, I'm not very inclined to include them here.

I guess that makes sense 👍🏻

**Comment by mikebattista** [comment]
I added the bthguid.h GUIDs so they will be available in the next release.
