### ISSUE TITLE
why define NTSTRSAFE_USE_SECURE_CRT as 0 here?

### ISSUE THREAD

**Issue by UMU618** [microsoft/wdkmetadata#62]
https://github.com/microsoft/wdkmetadata/blob/1ac0dd0719f19196334de12cf2a6dec20316d440/generation/WDK/RecompiledIdlHeaders/km/ntstrsafe.h#L80-L85

https://github.com/microsoft/wdkmetadata/blame/1ac0dd0719f19196334de12cf2a6dec20316d440/generation/WDK/RecompiledIdlHeaders/km/ntstrsafe.h#L82

Why there are all 0?

**Comment by mikebattista** [comment]
I'm not sure but these are the original header files. Are there any changes required in the metadata here? Or are you questioning the behavior in the WDK itself?
