### ISSUE TITLE
Missing Bcrypt provider functions

### ISSUE THREAD

**Issue by Amit-L** [microsoft/wdkmetadata#81]
Hello!

Are below bcrypt functions from Bcrypt_provider.h getting supported ?
This is blocking usage of registration/unregistration in cswin32 without which one cant make use of any bcrypt or ncrypt functions using custom provider.

1. BCryptRegisterProvider
2. BCryptUnregisterProvider
3. BCryptAddContextFunctionProvider
4. BCryptRemoveContextFunctionProvider

**Comment by riverar** [comment]
Was added in upstream metadata already 👍 https://github.com/microsoft/win32metadata/pull/1997 Should be in the next release, if not already out. (Then has to trickle down into CsWin32, Rust, etc.)
